=== saardude/Barton/australia/data/schema/facets.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://culegeri.local/australia/schema/facets.schema.json",
  "title": "Facets",
  "description": "facets.json: for each facet, a map of value -> number of songs. Keys are sorted. Null values are counted under the key 'null'.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "_meta",
    "decade",
    "year",
    "kind",
    "state",
    "town",
    "newspaper",
    "songbook",
    "singer",
    "collector",
    "author",
    "hasNotation",
    "hasMasthead",
    "hasMidi",
    "hasAudio",
    "yearFrom"
  ],
  "properties": {
    "_meta": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "songCount"
      ],
      "properties": {
        "songCount": {
          "type": "integer",
          "minimum": 0
        },
        "builtWith": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "decade": {
      "$ref": "#/$defs/countMap"
    },
    "year": {
      "$ref": "#/$defs/countMap"
    },
    "kind": {
      "$ref": "#/$defs/countMap"
    },
    "state": {
      "$ref": "#/$defs/countMap"
    },
    "town": {
      "$ref": "#/$defs/countMap"
    },
    "newspaper": {
      "$ref": "#/$defs/countMap"
    },
    "songbook": {
      "$ref": "#/$defs/countMap"
    },
    "singer": {
      "$ref": "#/$defs/countMap"
    },
    "collector": {
      "$ref": "#/$defs/countMap"
    },
    "author": {
      "$ref": "#/$defs/countMap"
    },
    "hasNotation": {
      "$ref": "#/$defs/countMap"
    },
    "hasMidi": {
      "$ref": "#/$defs/countMap"
    },
    "yearFrom": {
      "$ref": "#/$defs/countMap"
    },
    "hasMasthead": {
      "$ref": "#/$defs/countMap"
    },
    "hasAudio": {
      "$ref": "#/$defs/countMap"
    }
  },
  "$defs": {
    "countMap": {
      "type": "object",
      "additionalProperties": {
        "type": "integer",
        "minimum": 0
      }
    }
  }
}

=== saardude/Barton/australia/data/facets.json
{
  "_meta": {
    "builtWith": "australia/scraper/src/build.js",
    "songCount": 1021
  },
  "author": {
    "A CELT": 1,
    "A SHEPHERD. Broken River": 1,
    "A SPITALFIELDS WEAVER": 1,
    "A SUFFERER": 1,
    "A. A": 1,
    "A. B. Paterson": 1,
    "A. CAREY": 1,
    "A. E. YARRA": 1,
    "A. J. SIMPSON": 1,
    "A. L. Gordon": 1,
    "A. L. Lloyd, From London": 1,
    "A. P.": 1,
    "A. W. Davis": 1,
    "ALAN QUEALE": 1,
    "ALBATROSS": 1,
    "Adelaide": 1,
    "American": 1,
    "Anambaba": 2,
    "Argyle": 1,
    "Aristine Anderson": 1,
    "Arm Chair": 1,
    "BANNERMAN. Maryborough": 1,
    "BERTRAM. O. EYRE": 1,
    "BILL IGHTHAM.": 1,
    "BILLABONG JIM": 1,
    "BLACKBOY": 2,
    "BRANGZA": 1,
    "BUSHIE BILL.": 1,
    "Bathurst": 1,
    "Bauple": 1,
    "Ben Hall's": 1,
    "Bernard Barton": 1,
    "Bill Casey": 1,
    "Blackall. G. CAMERON LOWES": 1,
    "Bowen ELSIE KEMP": 1,
    "Brisbane": 1,
    "Budgerum.": 1,
    "Bundi": 1,
    "Busselton": 1,
    "By John Thompson": 1,
    "C. ISAACSON": 1,
    "C. NEWTON. Duchess": 1,
    "C. R. E. Grainger": 5,
    "C. W. BECKETT": 1,
    "C.E.S": 1,
    "C.R.E.G": 1,
    "CALEB": 1,
    "CAPTAIN FAT": 1,
    "CHAS. A. PERRY": 1,
    "CLARENCE O": 1,
    "CLEGGS": 1,
    "COONATTO": 1,
    "COYYAN": 1,
    "CROOKED MICK": 1,
    "Camooweal. BERT COSTELLO": 1,
    "Cecil Poole": 1,
    "Charles Augustus Flower": 1,
    "Charles Flower": 1,
    "Charles Mackay": 1,
    "Circle Valley": 1,
    "Clancy's Mate": 1,
    "Cooma": 1,
    "Curro.": 1,
    "D. D. K. McG": 1,
    "D.B.G": 1,
    "D.D": 1,
    "DOROTHY HEWETT": 1,
    "Dartmoor": 1,
    "Delungra": 1,
    "Dorothy Richardson.": 1,
    "Duchess. C. Newton": 1,
    "E J.S": 1,
    "E. A. RENVILLE": 1,
    "E. Beck": 1,
    "E. COLWELL": 1,
    "E. DODD": 1,
    "E. E. GEORGE": 1,
    "E. F. RUSSELL": 1,
    "E. H. D": 1,
    "E. Pike": 1,
    "E. S. SORENSON": 1,
    "E. S. Sorenson": 1,
    "E.R.I": 1,
    "EBENEZER ELLIOTT": 1,
    "ELIZA COOK": 2,
    "ERNEST CROSBY Rhinebeck. N.Y": 1,
    "Ed C": 1,
    "Edinburgh J.G": 1,
    "Edmund Fisher": 1,
    "Edward Wilbur Mason": 1,
    "Eileen Clinch": 1,
    "El Dorado": 1,
    "F.B": 1,
    "Flinders River. S.L": 1,
    "G. F. ALTHOFER": 1,
    "G. Spencer Briggs": 1,
    "GAWLER": 1,
    "GEOFFREY PAVEY": 1,
    "GILROONEY": 1,
    "GLENROWAN": 1,
    "GRASSIE": 1,
    "Geelong": 1,
    "H. H": 1,
    "H. HEALEY": 1,
    "H. McE": 1,
    "H. N. Murray": 1,
    "H.C.C": 1,
    "H.C.Hodge": 1,
    "H.F.B": 1,
    "H.S.B.": 1,
    "HOBO.": 1,
    "Harold Stevens": 1,
    "Harry Stafford": 1,
    "Harvey. B": 1,
    "Henry Chadwick": 1,
    "Henry E. Butler": 3,
    "Henry Lawson": 2,
    "Hobart Town": 1,
    "Horace Flower": 1,
    "Howard": 1,
    "Hughanden BERT DUNNE": 1,
    "Hughenden. BERT DUNNE": 1,
    "Hughenden. Bert Dunne": 1,
    "Humula": 1,
    "Indianapolis Journal": 1,
    "J. A. ANDREWS": 1,
    "J. DARK": 1,
    "J. H. COKBETT": 1,
    "J. J. Oakford": 1,
    "J. L": 1,
    "J. Noble": 1,
    "J.B": 1,
    "J.C": 1,
    "J.H.C.G": 1,
    "J.L": 1,
    "JACK": 1,
    "JULIAN STUART": 1,
    "JUSTITIA": 1,
    "Jack Bradshaw": 1,
    "Jack Crossland": 1,
    "Jack Moses": 1,
    "Jack Ritchie, Dubbo": 1,
    "James Riley": 1,
    "Jax.": 1,
    "Jean Bell": 1,
    "Jeff": 1,
    "Jim Connell": 1,
    "Jingle Jill": 1,
    "Joan Coleman": 1,
    "Joan Lynravn": 1,
    "John Alexander MacPherson": 1,
    "John Kells Ingram": 1,
    "John M'Lean, Coal-Miner": 1,
    "John Neilson": 1,
    "Jupiter Tonans, Wampy Wampy Flats": 1,
    "K. D. STARR": 1,
    "KARL KENNETT": 1,
    "Kuranda. EFFIE PIKE": 1,
    "L. A. Coplan, B.Sc": 1,
    "L. Chaplin": 1,
    "LAWRENCE HOLSTEIN": 1,
    "LOUIS M": 2,
    "Leilavale. P. JAMES IRVINE": 1,
    "Lilian Millar": 1,
    "Liverpool": 1,
    "London Workman's Times": 1,
    "Longreach": 1,
    "Lu Bricant": 1,
    "M. Forest": 1,
    "M. G. LEASK": 1,
    "M. MacD": 1,
    "M.O'G": 1,
    "M.R": 1,
    "MAB": 1,
    "MARCUS": 1,
    "MARY GILMORE": 1,
    "MEDDA": 1,
    "MLEE.": 1,
    "MONA MARIE. Ballarat": 1,
    "MOPOKE": 1,
    "Mary Sarsfield Gilmore": 1,
    "Maryborough": 1,
    "May Kidson": 1,
    "Meekatharra": 1,
    "Melbourne Punch": 1,
    "Melbourne. W. A. Tainah": 1,
    "Merewether": 1,
    "Michael Scanlon of Chicago": 1,
    "Miriam Vale. XIX": 1,
    "Miss Gore": 1,
    "Morning Chronicle": 1,
    "Mrs Norton": 1,
    "N.B": 1,
    "N.S.W. RIVERINA": 1,
    "NETTA WALKER": 1,
    "Namoi River": 1,
    "Nation": 1,
    "Ned McElligot": 1,
    "O. M.": 1,
    "OWEN MAGUIRE": 1,
    "Orange": 1,
    "P.C.B. Townsvllle": 2,
    "PAUL CUPID": 1,
    "PROSPECT GOOD": 1,
    "PUNCH": 1,
    "Paterson": 1,
    "Paul Cupid": 2,
    "Penrith. E.H. DUNLOP": 1,
    "Perth": 1,
    "Peter Graeme": 1,
    "Philip P. Bliss": 1,
    "Port Adelaide": 1,
    "Proserpine.--W.P": 1,
    "Q": 2,
    "Q. Anderson's Creek": 1,
    "R. D. Joyce": 1,
    "R. S. Hawker": 1,
    "R. S. TAIT": 1,
    "REG. A. FINNEGAN": 1,
    "ROBERT BRISSENDEN": 1,
    "ROSE OF COGMILLS": 1,
    "Richmond": 2,
    "Richmond. STATION HAND": 1,
    "Rifum": 1,
    "Robert Anderson": 1,
    "Robert Nicholl": 1,
    "Robert Stewart": 1,
    "Rocky Diggings": 1,
    "Ronald Stewart": 1,
    "Rose E. Sharland": 1,
    "S. A. POTTER": 1,
    "SENOJ": 1,
    "SNOOKS": 1,
    "STUMPY TAIL": 1,
    "SWINBURNE": 1,
    "Saul Mendelsohn": 1,
    "Shoalhaven News": 1,
    "St. Lawrence BILLEYRE": 1,
    "Stephen Foster": 1,
    "Stephens": 1,
    "Stuart Town": 1,
    "Swanfels": 1,
    "Sydney": 1,
    "T.D. O'CONNOR": 1,
    "T.D.B.": 2,
    "T.I": 1,
    "T.R.F.A.": 1,
    "T.W.ORCHARD": 1,
    "THE PILOT THAT WEATHERED THE STORM": 1,
    "THE SCOUT": 1,
    "THEO. C. HENLEY": 1,
    "THOMAS LOUIS BUVELOT ESSON": 1,
    "TOP T.": 1,
    "TURNOVER": 1,
    "Tarwong": 1,
    "The Biz\" Newspaper Wednesday": 1,
    "The Mopoke": 1,
    "Thomas C. Irwin": 1,
    "Tom Black": 1,
    "Toronto Weekly Globe": 1,
    "Townsville. JAX": 1,
    "Tumut": 1,
    "UNION GIRL": 1,
    "Upon St. Leonards": 1,
    "Vic": 1,
    "Vic. Warrana": 1,
    "W. A. PEEKE": 1,
    "W. B. Livesey": 1,
    "W. BOLLEN": 1,
    "W. H. LEVY": 1,
    "W. J": 1,
    "W. L. RYLAND": 1,
    "W. M. Fleming": 1,
    "W. N. C": 1,
    "W. Nutts": 1,
    "W. R. RILEY": 1,
    "W. T. Goodge": 1,
    "W.B.S": 1,
    "W.J.E": 1,
    "W.M.F": 1,
    "WALTER GEO. EDMUNDS": 1,
    "WATSON": 1,
    "WM. DELANDRE": 1,
    "Wanderer": 1,
    "Warwick. J. L. TOOTH": 1,
    "Wendy Lowenstein": 1,
    "Wereallmixedupxeduplikethis": 1,
    "William H Murray": 1,
    "Yabtree": 1,
    "a Railway Workman": 1,
    "a Shoalhaven Bard": 1,
    "null": 711,
    "the Man from Jugiong": 3
  },
  "collector": {
    "Alan Scott": 1,
    "Alex Hood": 2,
    "Bob Michell": 2,
    "Dr Percy Jones": 1,
    "Edgar Waters": 1,
    "Ian Coggins": 1,
    "Ian White": 1,
    "John Manifold": 3,
    "John Meredith": 11,
    "Laura Smith": 1,
    "Lloyd Robson": 1,
    "Lucy Broadwood": 2,
    "Max Brown": 1,
    "Mercedes Birkbeck": 1,
    "Norm O'Connor": 3,
    "Ron Edwards": 1,
    "Russel Ward": 2,
    "Stan Arthur": 1,
    "null": 986
  },
  "decade": {
    "1790s": 1,
    "1810s": 1,
    "1820s": 11,
    "1830s": 22,
    "1840s": 28,
    "1850s": 35,
    "1860s": 41,
    "1870s": 51,
    "1880s": 59,
    "1890s": 161,
    "1900s": 146,
    "1910s": 113,
    "1920s": 106,
    "1930s": 99,
    "1940s": 36,
    "1950s": 32,
    "1960s": 21,
    "1970s": 1,
    "1980s": 6,
    "2010s": 1,
    "null": 50
  },
  "hasAudio": {
    "no": 1014,
    "yes": 7
  },
  "hasMasthead": {
    "no": 319,
    "yes": 702
  },
  "hasMidi": {
    "no": 958,
    "yes": 63
  },
  "hasNotation": {
    "no": 705,
    "yes": 316
  },
  "kind": {
    "poem": 43,
    "song": 543,
    "unknown": 435
  },
  "newspaper": {
    "Adelaide Observer": 6,
    "Advocate": 2,
    "Age": 4,
    "Albury Banner and Wodonga Express": 2,
    "Alexandra Times": 2,
    "Alexandra and Yea Standard and Yarck, Gobur, Thornton and Acheron Express": 1,
    "Argus": 3,
    "Armidale Chronicle": 1,
    "Armidale Express and New England General Advertiser": 2,
    "Australasian": 4,
    "Australasian Chronicle": 4,
    "Australian": 1,
    "Australian Town and Country Journal": 5,
    "Australian Worker": 6,
    "Australian Workman": 1,
    "Avoca Mail": 1,
    "Bacchus Marsh Express": 1,
    "Ballarat Courier": 1,
    "Ballarat Star": 1,
    "Bathurst Daily Argus": 1,
    "Bathurst Free Press and Mining Journal": 1,
    "Bathurst Times": 1,
    "Beaudesert Times": 2,
    "Bell's Life": 2,
    "Bendigo Advertiser": 3,
    "Bent's News and Tasmanian Register": 1,
    "Blackwood Times": 1,
    "Blue Mountain Echo": 1,
    "Blue Mountain Star": 1,
    "Border Watch": 2,
    "Bowral Free Press": 1,
    "Bowral Free Press and Berrima District Intelligencer": 1,
    "Braidwood Dispatch and Mining Journal": 2,
    "Brisbane Courier": 1,
    "Bunbury Herald": 3,
    "Bunbury Herald and Blackwood Express": 1,
    "Bunyip": 5,
    "Burra Record": 1,
    "Burrowa News": 1,
    "Cairns Post": 4,
    "Camperdown Chronicle": 1,
    "Canowindra Star and Woodstock Recorder": 1,
    "Catholic Press": 3,
    "Central Queensland Herald": 1,
    "Chronicle": 2,
    "Clarence and Richmond Examiner": 2,
    "Clipper": 1,
    "Coffs Harbour Advocate": 2,
    "Colonial Times": 2,
    "Colonist": 1,
    "Colonist and Van Diemen's Land Commercial and Agricultural Advertiser": 1,
    "Cornwall Chronicle": 3,
    "Country Life Stock and Station Journal": 1,
    "Critic": 1,
    "Daily Herald": 1,
    "Daily Mercury": 1,
    "Daily News": 1,
    "Daily Standard": 2,
    "Daily Telegraph": 1,
    "Darling Downs Gazette and General Advertiser": 1,
    "Deniliquin Independent": 1,
    "Direct Action": 1,
    "Dungog Chronicle : Durham and Gloucester Advertiser": 1,
    "Euroa Advertiser": 1,
    "Evening Journal": 5,
    "Evening News": 6,
